### ISSUE TITLE
Section feature

### ISSUE THREAD

**Issue by proLETARi** [ngs-doo/TemplaterExamples#12]
Hi,
Im trying to use section feature but the output generated is always showing the two tables template. Im using as the example located at Intermediate/WordTables.
Please could you help me giving me any clue respecting that.

template: [1 Solicitud_template.docx](https://github.com/ngs-doo/TemplaterExamples/files/4021091/1.Solicitud_template.docx)
output: [1 Solicitudx.docx](https://github.com/ngs-doo/TemplaterExamples/files/4021098/1.Solicitudx.docx)

Cheers.

**Comment by zapov** [comment]
Your template has no sections so Templater cannot use the section feature.
You can view sections in the outline or draft view of the document.
There is an example here: https://github.com/ngs-doo/TemplaterExamples/blob/master/Intermediate/WordTables/template/Tables.docx which has sections around the tables so it works as expected.

To add such a section use Layout -> Breaks -> Continuous

**Comment by proLETARi** [comment]
Hi @zapov,

Thank you so much for your help, now my output is as expected, table template hidding depends if my list is empty or not.

[1 Solicitudx.docx](https://github.com/ngs-doo/TemplaterExamples/files/4022043/1.Solicitudx.docx)

But the content in tags aren't replacing with the data of my class. Any suggest why this is hapennig, maybe its because im using observablecollection instead of datatable like in your example?

Please help me.

Cheers.

**Comment by zapov** [comment]
ObservableCollection should work fine. Are your methods/properties public? Try to create reproducible with JSON: https://github.com/ngs-doo/TemplaterExamples/releases/tag/v4.0.0
And if that does not work, paste the JSON here.

**Comment by proLETARi** [comment]
Sure the methos and propertis are public. The're structured like in your example:

![image](https://user-images.githubusercontent.com/9972954/71824014-8be41700-3066-11ea-8a51-d573d82644c8.png)

In fact the class items fill correctly in word output generated, just the part in sections aren't filling.

**Comment by proLETARi** [comment]
Hi @zapov,

And the json generated as you recommended: 

[
    {
        "items": [
            {
                "curso": "Matemática",
                "nota": 20
            },
            {
                "curso": "Calculo I",
                "nota": 18
            },
            {
                "curso": "Redacción",
                "nota": 19
            }
        ],
        "table": [
            {
                "Name": "Name1",
                "Description": "Description 1"
            }
        ],
        "ruc": "10474132540",
        "poliza": "P022213341"
    }
]

And the output generated is correctly filled, but why this section feature just working with json data? There are any issue working with class? Cause like i wrote u the class items fill correctly and just table not. 

Anyway i will have to work with json. Thanks for your help.

**Comment by zapov** [comment]
Your class works fine with the last template you uploaded. Maybe you are using some other template as this one does not have `[[items` inside, only `[[table`

**Comment by proLETARi** [comment]
Its ok @zapov. 
Thanks for your time and help.

Cheers.

**Comment by proLETARi** [comment]
Hi @zapov 

Im trying to hide section with this json 

[
    {
        "items": [],
        "table": [
            {
                "Name": "Name1",
                "Description": "Description 1"
            },
            {
                "Name": "Name2",
                "Description": "Description 2"
            },
            {
                "Name": "Name3",
                "Description": "Description 3"
            }
        ],
        "ruc": "10474132540",
        "poliza": "P022213341"
    }
]

When .process(data) im getting this exception:

![image](https://user-images.githubusercontent.com/9972954/72686152-90c1b580-3abf-11ea-8ad6-27c428ea8bbe.png)

So how can i have to empty list to show "no results found" section.
Please help me.

**Comment by zapov** [comment]
I tried replicating your issue but no luck. Can you upload minimum example project showing the problem?

**Comment by proLETARi** [comment]
Sure @zapov, here is the example, inside folder project exists an word document called "1 Solicitud_template.docx" as template

[templater-test.zip](https://github.com/ngs-doo/TemplaterExamples/files/4092479/templater-test.zip)

Please any suggestions tell me.
Thanks.

**Comment by zapov** [comment]
The exception is not coming from Templater, but rather from that CollapseNonEmpty plugin you registered. So you can put in a breakpoint there and see the reason for exception.
The problem is at line

    var xx = dt.Length;

because dt is null

**Comment by proLETARi** [comment]
You're right, doing some changes now works.
Thank you so much.
Greetings.
