### ISSUE TITLE
Excel Tabs

### ISSUE THREAD

**Issue by danmcpherson** [ngs-doo/TemplaterExamples#15]
I'm looking for an example where I can remove an existing Excel worksheet (tab). Basically, I would like it to work like "collapseif" works in Word. That I could hide a tab should a value passed in be equal to a certain value.

**Comment by zapov** [comment]
Hm... it seems there is not yet such an example. I'll look into adding it later, but for now you can use https://github.com/ngs-doo/TemplaterExamples/tree/master/Advanced/DepartmentReport

and add explicit resize to see how it works... eg:

    using (var doc = Configuration.Factory.Open(fis, fos, "xlsx"))
    {
      doc.Templater.Resize("department.code", 0);
      doc.Process(GetCompany());
    }

Your tag does not need to be in the sheet name, in which case you'll have to add :sheet or :page metadata to it, so Templater interprets it as an action on the whole sheet.

**Comment by zapov** [comment]
There is now such example in: https://github.com/ngs-doo/TemplaterExamples/tree/master/Intermediate/Formulas
Hopefully that clarifies how to use it

**Comment by danmcpherson** [comment]
Thanks very much.
