### ISSUE TITLE
Text box (Shape) colors

### ISSUE THREAD

**Issue by i-marasa** [ngs-doo/TemplaterExamples#16]
Hi,,
Is there away to control on shape fill and border color using c#?
for example: text box background color.

**Comment by zapov** [comment]
In the vanilla version, not really. You would need to extend the library and add support for this special handling. I might consider such extension in the future, but currently there is none.

You have two alternative options:
  * use something which you can color, like a cell of a table: https://github.com/ngs-doo/TemplaterExamples/tree/master/Beginner/DataSet%20(.NET)
  * paste entire text box through XML type, along the lines of: https://github.com/ngs-doo/TemplaterExamples/tree/master/Intermediate/HtmlToWord

**Comment by i-marasa** [comment]
Thanks, 
using HTML works,,
