### ISSUE TITLE
Is it possible to use multiple tables with same column names in DataSet?

### ISSUE THREAD

**Issue by picolino** [ngs-doo/TemplaterExamples#17]
I have this code:

```cs
var ds = new DataSet();

var dt1 = new DataTable("Table1");
dt1.Columns.Add("Column1");
dt1.Columns.Add("Column2");

var dt1row = dt1.NewRow();
dt1row["Column1"] = 100;
dt1row["Column2"] = 200;
dt1.Rows.Add(dt1row);

var dt2 = new DataTable("Table2");
dt2.Columns.Add("Column1");
dt2.Columns.Add("Column2");

var dt2row = dt2.NewRow();
dt2row["Column1"] = 400;
dt2row["Column2"] = 500;
dt2.Rows.Add(dt2row);

ds.Tables.Add(dt1);
ds.Tables.Add(dt2);

using var inputFileStream = new FileStream("template.docx", FileMode.Open);
using var outputFileStream = new FileStream("result.docx", FileMode.Create);
using var templateDocument = Configuration.Builder.Build().Open(inputFileStream, outputFileStream, "docx");

templateDocument.Process(ds);
```

My template:
```
[[Column1]] [[Column2]]
```

And in the result `docx` file I always get `100` and `200` values from the first table. I want to be able to choose a specific table while export, like that:

```
[[Table1.Column1]] [[Table2.Column1]]
```

How can I achieve that?

**Comment by zapov** [comment]
The builtin DataSet processor does not try to do that as tables are often unnamed.

What you can do is in your code before calling Process method, convert such data sets into Dictionary objects which should give you the behavior you want. eg:

    var tables = new Dictionary<string, DataTable>();
    foreach (DataTable t in ds.Tables)
      tables[t.TableName] = t;
    templateDocument.Process(tables);

**Comment by picolino** [comment]
Oh, so simple. Pretty cool, thank you 🤗
