### ISSUE TITLE
Create a code example on how to register new tags

### ISSUE THREAD

**Issue by ErroneousFatality** [ngs-doo/TemplaterExamples#18]
I'm looking at the user manual and it's not entirely clear to me how to register a new set of tags ("«" "»").
Adding a code example of how to do it would help a lot of people in the future, I reckon.

**Comment by zapov** [comment]
Not sure I'm fully following your question...

There are only 3 predefined sets of tags: `[[tag]]`, `{{tag}}` and `<<tag>>`
You can configure those 3 sets: https://templater.info/apidocs/hr/ngs/templater/IDocumentFactoryBuilder.TagPattern.html

But you can't add a new one.

**Comment by ErroneousFatality** [comment]
Ah. My bad then, I thought it was possible. Thanks for the quick answer.
