### ISSUE TITLE
Multiple collapensenonempty use in template

### ISSUE THREAD

**Issue by proLETARi** [ngs-doo/TemplaterExamples#21]
Hello @zapov 

Im trying to use collapse or not in a template.
This is.
[template_test.docx](https://github.com/ngs-doo/TemplaterExamples/files/5164927/template_test.docx)

Variables tables is empty, so should be not showed, but when collapsenonempty is executed by second time to evaluate variable table its make appear again. 

[1 Solicitudx.docx](https://github.com/ngs-doo/TemplaterExamples/files/5164931/1.Solicitudx.docx)

Is there any way to prevent that? Help me please.

Greetings.

**Comment by zapov** [comment]
To avoid potential confusion can you provide small runnable reproducible?
Or change the example to use JSON and provide JSON example to run through JSON build: https://github.com/ngs-doo/TemplaterExamples/releases/tag/v4.5.0

**Comment by zapov** [comment]
Please let me know if this is still an issue in v5.0

**Comment by zapov** [comment]
v5.1 introduced more fine grained Handler API.
It should help with such issues if they are still relevant.

Please provide more info if this is still not working as expected.
