### ISSUE TITLE
How do I resize a table/list with an IFormatter plugin?

### ISSUE THREAD

**Issue by polvoblanco** [ngs-doo/TemplaterExamples#23]
Hi,

I am trying to take a JSON document, like:

```
{"departments" [{"id" "2",
                 "name" "Sales",
                 "_subs" {"id" "1",
                          "name" "Acme"}}
               {"id" "3",
                "name" "Support",
                "_subs" {"id" "1",
                         "name" "Acme"}}]}
```

And process it through an IFormatter plugin, with a tag like [[departments]:department]

The plugin takes the collection and returns a new collection where the value has been re-written as

`
["Acme/Sales" "Acme/Support"]
`

This works correctly, however, when I place the tag in a table or a list, instead of putting each department in a new row or a new bullet point, it displays it as above in a single cell/point.

Does the data have to be returned from the plugin with a specific type to correctly resize the table/list?

I'm using Clojure but can provide a code sample of my plugin if it will help.

Many thanks,

Paul

**Comment by zapov** [comment]
You can't do that via formatter, but you can via IHandler.

I'm sure it will be much easier if you transform maps and lists into different format before the processing,
Alternatively you can use specific IProcessor handlers for custom processing of some types.. which might be more natural way to handle such use case.

**Comment by polvoblanco** [comment]
Thanks, I want to avoid manipulating the source data if at all possible.

I have looked at the IProcessor but it seems to receive the full collection of data, not just the specific sub-collection.

So, I think an IHandler would be the best approach, do you have any examples that showcase IHandler?

**Comment by zapov** [comment]
There is an example here: https://github.com/ngs-doo/TemplaterExamples/blob/master/Intermediate/WordTables/src/main/java/hr/ngs/templater/example/WordTablesExample.java
and here: https://github.com/ngs-doo/TemplaterExamples/blob/master/Intermediate/CollapseRegion/src/main/java/hr/ngs/templater/example/CollapseExample.java

But I can't say there is an example of using it to increase row count

**Comment by polvoblanco** [comment]
Thanks, I was able to figure it out from the examples.
