### ISSUE TITLE
Image replacer (using Alt Text) appears to not work correctly when image is copied inside document

### ISSUE THREAD

**Issue by fango256** [ngs-doo/TemplaterExamples#28]
Just ran into a situation where i believe the existing image replacement is replacing all images with the last image in the document despite them having different tags and images.

Repro:
1) Create data supporting two images [[Image1]], [[Image2]]
2) Add an image to template from any image source.
3) Update image alt text to match the first image [[Image1]]
4) Copy the image in the template
5) Update the alt text to the second image [[Image2]]
6) Process

Result:
Both images are [[Image2]]

Expected:
First image [[Image1]] second image [[Image2]].

Example Repo:
[TemplaterPictureBox.zip](https://github.com/ngs-doo/TemplaterExamples/files/5292115/TemplaterPictureBox.zip)

I think it's the copying of the image in the template that is causing the issue - however i think this will be a common use case when designing templates.

Cheers

**Comment by zapov** [comment]
Yeah, we just fixed that few days ago. It will be in next version.

For now the workaround is not to copy paste images, but rather always select dummy placeholder image which will get replaced.

**Comment by zapov** [comment]
v5.0 has been released
