### ISSUE TITLE
Low level API replacement across fixed and resized tags

### ISSUE THREAD

**Issue by polvoblanco** [ngs-doo/TemplaterExamples#29]
Using the low level API, how can you tell if a tag is on a fixed part of the page or the first (template) part of a resizable collection?

I understand that on the resized parts themselves you can check the metadata for _ci:r:_ci:r:#-# codes, however it is not clear how you distinguish between zero, one or more fixed tags and the first (template) tag of a resized set.

Thanks, Paul

**Comment by zapov** [comment]
Templater uses that internal metadata info only to check if tag is considered shared, in which case it will have same metadata value.
Other than that... there is not much info in there... they should be unique to distinguish between themselves.
