### ISSUE TITLE
Data inconsistencies

### ISSUE THREAD

**Issue by tecxx** [ngs-doo/TemplaterExamples#31]
Hello,
i'm very interested to put this library into our inhouse management software, but before we decide to go ahead and buy a license we'd like to get some basic tests working.

this is the word template:
![image](https://user-images.githubusercontent.com/4305825/98472351-c1abdc00-21f2-11eb-9ab4-faede5b813f6.png)

and this is the result:
![image](https://user-images.githubusercontent.com/4305825/98472371-ed2ec680-21f2-11eb-8beb-02575ec868f6.png)

- there are a total of 7 data rows in the data model (see counter in the table header) but only 5 show up in the resulting table. the remaining two have no "findings" in their linked list. but why is the entire table row gone because of this?
- for data row chk-135 and chk-132, for some reason the ".Count" function produces zero, while there is clearly a value in their  linked list (FND-102 and FND-95)
- i added a manually calculated field to make the error more visible

here's the simplified data model:

```
    public class ReportingRootObject
    {
        public Reporting_PlaceholderData Data;
        public List<Reporting_ScopeContainerChecks> checksInScope { get; set; }
    }
    public class Reporting_ScopeContainerChecks
    {
        public string scopeName;
        public List<Reporting_CheckInScope> scopeData { get; set; }
    }
    public class Reporting_CheckInScope
    {
        public string group;
        public string category;
        public string id;
        public string title;
        public string reasoning;
        public List<string> referenceUrls;
        public List<string> referenceUrlsMitre;
        public int rating;
        public int findingsCount;
        public List<Reporting_CheckTask> checkTasks { get; set; }
        public List<Reporting_Finding> findings { get; set; }
        public List<Reporting_Measure> measures { get; set; }
    }
```

and here's the debugger, to prove the data model is correct:
![image](https://user-images.githubusercontent.com/4305825/98472527-e05ea280-21f3-11eb-8ad9-284898f7eac3.png)

edit:
just remembered, this project is on .net 5 rc2. is this supported?

**Comment by zapov** [comment]
Hi @tecxx 

It should work fine on latest .NET

Can you please upload the template.
And it would be very helpful to provide some code to recreate the data, or JSON representing the same data.

**Comment by tecxx** [comment]
here is the stripped down template, removed all but the relevant parts
https://web.tresorit.com/l/zT5AQ#1HNFzKegL9t1EIqENW8D5Q
for code&json i try to provide a sample project in the coming days

**Comment by zapov** [comment]
Tnx.
I took a look at your example... and there are two main issues:
1) you probably want to put `checksInScope.scopeData.findings` in something resizable, like a list (or nested table)
2) there is a bug with .Count handling in `checksInScope.scopeData.findings` which I'll fix in next version, but you can work around it like you did, or via some other plugin.

So the main problem in 1) is that when there are 0 findings, resize(tags, 0) gets called, which deletes the whole row. You probably want to remove only the part related to finding listing, but for that to work as expected you need to put it into a nested resizable object

The problem 2) looks like a bad handling of resize 0 and property of a list. You can actually make a workaround by using `{{checksInScope.scopeData.findings}:count}` to avoid adding the extra findingsCount property on a list... by registering a formater which will return number of elements in a collection

**Comment by zapov** [comment]
Also, instead of using different nesting element, you can put the entire findings in second row, merge cells in other columns and setup borders on table/cells.
[TemplatePentestReport.docx](https://github.com/ngs-doo/TemplaterExamples/files/5508962/TemplatePentestReport.docx)

I've tested with this JSON:
```
{"checksInScope":{"scopeData":[
	{"id":"1","title":"t1","findingsCount":2,"findings":[
		{"id":"f1","title":"ft1","rating":"fr1"},
		{"id":"f2","title":"ft2","rating":"fr2"}
	]},
	{"id":"2","title":"t2","findingsCount":0,"findings":[
	]},
	{"id":"3","title":"t3","findingsCount":3,"findings":[
		{"id":"f5","title":"ft5","rating":"fr5"},
		{"id":"f6","title":"ft6","rating":"fr6"},
		{"id":"f7","title":"ft7","rating":"fr7"}
	]},
]}}
```

**Comment by tecxx** [comment]
thanks for your prompt reply. adding a table for findings worked (and now also .Count shows the correct result). now i understand what you mean in your documentation with "table without borders", so in case something repeats we should simply add a "dummy" table as a repeating element?

regarding your second reply, i tried that as well and understand what you suggest. could you check the file that you uploaded though? it contains just my original table, was that your intention?

thanks again - i will close this and continue some more tests.

**Comment by zapov** [comment]
Yes, I removed everything else, just to showcase that part

**Comment by tecxx** [comment]
i'm still not over the basics, could you be so kind and answer me one more question.

i am trying to show "no data" when a collection is empty. based on the documentation i should use [[tag]:empty(string)]
while this works when the collection is actually empty ("no data" is shown), it displays a very strange output when data exists:

![image](https://user-images.githubusercontent.com/4305825/98741122-60c80380-23ac-11eb-8ab9-9b190c4b5a15.png)

![image](https://user-images.githubusercontent.com/4305825/98741222-94a32900-23ac-11eb-981d-24d423771459.png)

**Comment by zapov** [comment]
Its calling to string on the object. You need to put additional metadata on it (or write your own instead of empty) - eg: hide
There is an example here: https://github.com/ngs-doo/TemplaterExamples/tree/master/Intermediate/CollapseRegion
