### ISSUE TITLE
Content in table do not appear in navigation

### ISSUE THREAD

**Issue by waqasraz** [ngs-doo/TemplaterExamples#32]
Then adding content inside a table so that it is collapsable, this content does not appear in TOC. Any alternative to the content being inside the table?

![image](https://user-images.githubusercontent.com/1761304/100846655-d2690e00-348f-11eb-8dc8-8b5770e1cb1e.png)

**Comment by zapov** [comment]
You could use a section breaks to make a collapsable region, but not sure if that will work.
TOC is being treated in a special way, although some restrictions should be lifted.

**Comment by zapov** [comment]
v5.1.1 has been released which supports removal of TOC
But since you did not ask about TOC, but rather navigation I suppose your issue is resolved (which worked as expected even previously).

If there is something more, please provide more info.
