### ISSUE TITLE
Collapase table row if data is null or empty

### ISSUE THREAD

**Issue by chrisgiordano-kp** [ngs-doo/TemplaterExamples#34]
Hi,

I'm facing a problem. I need to collapse a table's row when the data of this row is null or empty.

I tried to search for this information but i didn't find it. 

I saw that you can collapse a block when the value is null but Is it possible to achieve this with a row in a table ?

Thank you for your help.
Christophe

**Comment by zapov** [comment]
Yes, its possible.
If there is an appropriate tag, Templater will consider that row of a table collapsable.
You can find relevant examples here:
https://github.com/ngs-doo/TemplaterExamples/tree/master/Beginner/DataSet%20(.NET)
https://github.com/ngs-doo/TemplaterExamples/tree/master/Intermediate/WordTables

Also, this example is covered in introduction video at: https://templater.info/documents
It might be helpful to watch it.

Regards,
Rikard

**Comment by chrisgiordano-kp** [comment]
Dear Rikard,

thank you for your answer.

I think i understood how i should handle it. 
I was able to collapse a row based on an empty collection.

I just need now to manage the display when the collection is not empty :)

Thank you for your help !
Christophe
