### ISSUE TITLE
Inconsistent dynamic resizing 

### ISSUE THREAD

**Issue by str-00** [ngs-doo/TemplaterExamples#38]
Hi,

I have this table that dynamically resize for the columns, group cells and group rows 
![image](https://user-images.githubusercontent.com/83416591/116577808-b9fb0380-a908-11eb-9931-96d5b5d37adf.png)

All my data shows up fine except that the whole table is squeezed to the left and the row for the group name and group cells do not line up to the rest of the table
![image](https://user-images.githubusercontent.com/83416591/116577549-7a341c00-a908-11eb-929d-ac4ad4f706d6.png)

Template: [GenericGridTemplater.docx](https://github.com/ngs-doo/TemplaterExamples/files/6399846/GenericGridTemplater.docx)
JSON: [StockValuationGridJson.txt](https://github.com/ngs-doo/TemplaterExamples/files/6399848/StockValuationGridJson.txt)

**Comment by zapov** [comment]
Tnx for the report. I'll look what can be done here.

**Comment by zapov** [comment]
I've improved support for this and will include it in next release.
You can download snapshot [here](https://tools.dsl-platform.com/NGS.Templater.zip)

btw. you will have to adjust template to get output you probably expect
