### ISSUE TITLE
Default tag not repeating with template using :page

### ISSUE THREAD

**Issue by DanielWalter-MXP** [ngs-doo/TemplaterExamples#39]
Hello.
We have a data structure like this one:
```
{
  [ MyCompany: {
      [ Name: string,
        Address: string
       ]},
    Fiscal: List({
      [ Number: int,
       TotalValue: decimal,
       Item: List({
               [ Code: string,
                 Value: decimal
                ]})
      ]})
]}
```

If creating a model where there is multiple `Fiscal` and just one `MyCompany` the tags inside `MyCompany` doesn't repeat in the rest of the report.

Attached are the example, result and desired result.
[Example](https://github.com/ngs-doo/TemplaterExamples/files/6509648/example.docx)

[Result generated](https://github.com/ngs-doo/TemplaterExamples/files/6509647/Result.docx)

[Result desired](https://github.com/ngs-doo/TemplaterExamples/files/6509646/Result.desired.docx)

**Comment by zapov** [comment]
Can you please upload JSON used for this example data?

**Comment by DanielWalter-MXP** [comment]
Yes, of course.


[Example.txt](https://github.com/ngs-doo/TemplaterExamples/files/6524758/Example.txt)

**Comment by zapov** [comment]
The output I get looks kind of like what you expect?
I did had to fix template a bit since your "tags" are not really valid. And maybe putting page metadata at the correct place fixed the problem?

[example.docx](https://github.com/ngs-doo/TemplaterExamples/files/6524799/example.docx)

[templater-output.docx](https://github.com/ngs-doo/TemplaterExamples/files/6524803/templater-output.docx)

**Comment by DanielWalter-MXP** [comment]
Here it is the json model with the data I found the issue (maybe it has to do with the size?) and the template used
[jsonExample.txt](https://github.com/ngs-doo/TemplaterExamples/files/6524975/jsonExample.txt)
[Template-Example.docx](https://github.com/ngs-doo/TemplaterExamples/files/6524976/Etiqueta_Transporte_dest.igual.docx)

**Comment by zapov** [comment]
Hm, I'll look next week what can be done about this.

You have a problem with your template (one of the tag is wrong) - this is easily reported by Templater Editor, might be worth upgrading your license as you also get debugging support with it.

You can work around this problem for now by changing input JSON a bit (putting Minha section before NotaFiscal).
And you don't need `:page` metadata on all those tags, just first one will suffice

**Comment by zapov** [comment]
There is also one more workaround. You don't need to reorder JSON, but instead of passing a collection, just pass the single element from the collection. It works as expected in that case.

**Comment by zapov** [comment]
This should now work out of the box. You can download the latest snapshot from [here](https://tools.dsl-platform.com/NGS.Templater.zip)

btw. this `:page` metadata is something old which should really be deprecated. It will work only for simple use cases. It would be better to put a tag outside of table with `:hide` metadata which would result in the same behavior

**Comment by DanielWalter-MXP** [comment]
Don't seem to have worked for me, but that could just be that I did something wrong to replace the file.

Considering that the `:page` metadata is deprecated I won't be pushing too into it and change the way the data is formulated to templater.

**Comment by zapov** [comment]
The jsonExample.txt and Template-Example.docx should work out of the box with the snapshot I linked.
The hide doesn't work on the regular version either. It will only work with workarounds (don't send a top level collection, just rather the object from it). Fix is mainly for that problem

**Comment by DanielWalter-MXP** [comment]
I have fixed the model to make more sense, thank you for your time and support.
