### ISSUE TITLE
How License works?

### ISSUE THREAD

**Issue by marc-dev1** [ngs-doo/TemplaterExamples#41]
Hello,

I have bought the license for 1 developer and I would like to know if the license should be applied exclusively on the server where the business api has been deployed. How does the license really work?
Could you give me an indication of how the team we are working on can work with the bookstore?

I will appreciate your kind response.

**Comment by zapov** [comment]
It should be applied within the application you develop. 
You can either add it 
  * explicitly: https://github.com/ngs-doo/TemplaterExamples/blob/master/Advanced/PowerQuery/src/Program.cs#L15
  * as embedded resource: https://github.com/ngs-doo/TemplaterExamples/blob/master/Beginner/WebExample%20(.NET)/TemplaterWeb.csproj#L98
  * or by referencing it from somewhere on the disk - by default it will look for templater.lic in the app folder
