### ISSUE TITLE
replacing image in word document

### ISSUE THREAD

**Issue by nporchis** [ngs-doo/TemplaterExamples#45]
Hello,

I try to update an image on a word document based on the "Existing images" chapter of the TemplaterDocumentation
![image](https://user-images.githubusercontent.com/47812679/158349489-7ffc53e9-8416-4987-950b-596af0e94460.png)

When processing the document with below code and Base64Image plugin the image is not replaced.

![image](https://user-images.githubusercontent.com/47812679/158349831-78ed02e1-6865-4e1a-8fbb-b657241a6189.png)

Any help would be very appreciated,
Thanks
Numa

Docx file used:
[GreAGre.docx](https://github.com/ngs-doo/TemplaterExamples/files/8251944/GreAGre.docx)

**Comment by nporchis** [comment]
Hello again,

When converting word document without compatibility mode i successfully can update alt text information.
With that correctly filled, processing is ok.

Thanks anyway.
Numa

**Comment by zapov** [comment]
Hi Numa,

I tried opening your file in different MS Office tools but they were unable to show this picture at all.
Which Office tools did you create it with? And can you still open the file uploaded in this issue?

**Comment by nporchis** [comment]
Hi Zapov,
No i don't have the picture either. 
But it's ok now without compatibility mode.
Thanks
