### ISSUE TITLE
Include HTML in templater

### ISSUE THREAD

**Issue by albertobelardi** [ngs-doo/TemplaterExamples#46]
I developed a custom convert to allow an html from an external data source to be converted within the docx document managed by templater. Within my HTML are images encoded in Base64 format. The procedure is abuonly successful if the HTML contains no images. What can I use to include html in a templater tag? Thank you.

**Comment by zapov** [comment]
Here is example of how to pass file with html extension into Word: https://github.com/ngs-doo/TemplaterExamples/tree/master/Intermediate/HtmlToWord
So you could create temporary file, pass it along, and then remove it at the end of procesing

**Comment by albertobelardi** [comment]
Ok thank you, when you use System.IO.FileInfo in C# the inject html text into document will be injected outside everything table, section and so on. Is possible to encapsulate the html text into a word table?

**Comment by zapov** [comment]
Not via that method. Only if you provide XML, but then you are rather limited in what you can paste.
