### ISSUE TITLE
Numbering in section

### ISSUE THREAD

**Issue by albertobelardi** [ngs-doo/TemplaterExamples#47]
I have this template, when it is rendered, the highlighted section: [[SolutionSystems.Groups.GroupDescription]] despite having neither numbering nor bullet when processed by template is created numbering 1.2.1. How can this be prevented?
![immagine](https://user-images.githubusercontent.com/25862755/170991446-176b9599-5b62-48af-ab38-142a44492edc.png)

**Comment by zapov** [comment]
Please upload the template. Its hard to tell anything without it

**Comment by zapov** [comment]
Did you managed to resolve this?
Can you upload the template and relevant test data/json or should I close this?
