### ISSUE TITLE
"Trial" text even after purchasing the license

### ISSUE THREAD

**Issue by albertobelardi** [ngs-doo/TemplaterExamples#51]
I purchased the Templater Solo Developer v7.x license, but the trial text is still present in some places in the generated docx document. I correctly integrated the templater.lic file received with the invoice. How can I fix this? Thank you very much.

**Comment by zapov** [comment]
Hi @albertobelardi 

if you are having problems setting up reference to file or resource,
I suggest trying to set it up explicitly like here: https://github.com/ngs-doo/TemplaterExamples/blob/master/Advanced/PowerQuery/src/Program.cs#L15
First line from license is email, second one is key.

Also make sure you are creating instances from this configured factory.

**Comment by albertobelardi** [comment]
Hi zapov,
the problem is still not solved even after putting the license code in the Build method. If it helps, the application that uses Templater 7.0.0 is ASP.NET based on the 4.8 framework. What else can I do? Thank you.

**Comment by zapov** [comment]
Please clone the project I referenced and put the license in there to verify its working in that project.
If that still doesn't work create a small reproducible project we can run and send it to support email.

**Comment by albertobelardi** [comment]
Hi
the licence works now. Thanks. How can I condition the display of the tables in the following image? SolutionSystems.Services.AutomationCellCertification is a list of objects in C#. Many thanks.

![image](https://user-images.githubusercontent.com/25862755/180454086-d9bb570b-26d2-4299-bdfa-b2afb6fd92f1.png)

**Comment by zapov** [comment]
You can fine relevant example here: https://github.com/ngs-doo/TemplaterExamples/tree/master/Intermediate/WordTables

There is also more info in user manual: https://templater.info/user-manual as page 67
