### ISSUE TITLE
Horizontal resize not working

### ISSUE THREAD

**Issue by str-00** [ngs-doo/TemplaterExamples#55]
I have this CSV template where I want a horizontal resize for 3 columns (Line number, Stock item, Qty) by order lines
![image](https://user-images.githubusercontent.com/83416591/185094203-94d50a62-a938-4bc1-b7bd-acfea9dddeeb.png)

The horizontal resize is not working and the result shows all order lines in separate rows instead of columns.
![image](https://user-images.githubusercontent.com/83416591/185094406-defb14a4-8ffc-4181-8812-8e57f91f556d.png)

CSV template: [InvoiceTest.csv](https://github.com/ngs-doo/TemplaterExamples/files/9358653/InvoiceTest.csv)
Test data: [InvoiceJson.txt](https://github.com/ngs-doo/TemplaterExamples/files/9358659/InvoiceJson.txt)
Result: [Result.csv](https://github.com/ngs-doo/TemplaterExamples/files/9358785/Result.csv)

Also, 
Is it possible to have a horizontal resize for a group of columns? 
Instead of having all Line Number columns together, then the Stock Item columns, then Quantity columns.
![image](https://user-images.githubusercontent.com/83416591/185096830-f5eac2d6-db1f-402b-ad52-ce3e41861edb.png)
I would like to have a set of columns for each order line.
![image](https://user-images.githubusercontent.com/83416591/185095978-84f87602-59c4-4f70-b920-554526a12e9a.png)

**Comment by zapov** [comment]
Yeah, some of the features are not implemented in CSV.
You'll have to use Excel if you want to get such behavior.

We plan on improving CSV, although don't have ETA at the moment.
Dynamic resize, config for separators and automatic quoting are some of the planned features.
