### ISSUE TITLE
Line break (\n) issue in pptx templates

### ISSUE THREAD

**Issue by phinc** [ngs-doo/TemplaterExamples#57]
Input:
- pptx template document with tag  {{tag}}
- data to replace the tag with value "text before line break  \n text after line break"

Expected output:
- pptx doc with 2 lines:
text before line break
text after line break

Real output:
- pptx doc has only the first line:
text before line break

Looking into pptx doc internals it's seen that the second line is rendered improperly and nested into the first one

> <a:r>
							<a:rPr lang="en-US" sz="1600" b="0" strike="noStrike" spc="-1" dirty="0">
								<a:solidFill>
									<a:srgbClr val="000000"/>
								</a:solidFill>
								<a:latin typeface="Fira Sans"/>
								<a:ea typeface="Arial"/>
							</a:rPr>
							<a:t>text before line break</a:t>
							<a:br/>
							<a:r>
								<a:rPr lang="en-US" sz="1600" b="0" strike="noStrike" spc="-1" dirty="0">
									<a:solidFill>
										<a:srgbClr val="000000"/>
									</a:solidFill>
									<a:latin typeface="Fira Sans"/>
									<a:ea typeface="Arial"/>
								</a:rPr>
								<a:t>text after line break</a:t>
							</a:r>
						</a:r>

**Comment by zapov** [comment]
Hi,

can you pls provide the output document (and a picture of the output)
I just tried it and it looks fine to me (by fine I mean its shown in 2 lines on Microsoft PowerPoint)

![image](https://user-images.githubusercontent.com/1181401/194078500-995f300b-e497-46c3-b182-f38c79cfc6db.png)

**Comment by phinc** [comment]
I've attached input template and json data and output file
[testLineBreak.pptx](https://github.com/ngs-doo/TemplaterExamples/files/9716454/testLineBreak.pptx)
[testLineBreak_6797307978397051756.pptx](https://github.com/ngs-doo/TemplaterExamples/files/9716456/testLineBreak_6797307978397051756.pptx)

**Comment by phinc** [comment]
input json data 
{
"tag": "text before line break \n text after line break"
}

**Comment by phinc** [comment]
I'm using Templater 7.1.0 java lib

**Comment by zapov** [comment]
Tnx for the bug report. Fixed it on master. I'll contact you for a fix

**Comment by zapov** [comment]
New version has been released. It fixes this problem.
