### ISSUE TITLE
Duplicate section

### ISSUE THREAD

**Issue by albertobelardi** [ngs-doo/TemplaterExamples#65]
Hi, I have a problem with the Templater process duplicating a section for me as in the screenshot I attached. Headings 1,2,3,4,5,6,7 are all level 1 however sections 2 and 4 are duplicated. How can this problem be resolved? 

Thank you

![image](https://user-images.githubusercontent.com/25862755/227260702-075ce910-6ed9-4479-b194-fdcf7ac22e4c.png)

This is the initial template that generates the document:

![image](https://user-images.githubusercontent.com/25862755/227261067-5a9c000d-2111-47de-9b20-452fc2bbb34a.png)

**Comment by zapov** [comment]
Hi @albertobelardi 
Its hard to tell without actual template or input data, ideally JSON.
I can only assume you have some tag out of place which ends up resizing more than you want.
If you have Templater Editor you could run it with debug option and it would tell you exactly when/why that happens.

**Comment by albertobelardi** [comment]
Hi @zapov 
I only have the "Developer Only" license, I don't have the Templater Editor, is there any other way to figure out where the problem is? I have invested many hours to find a solution, but I have not succeeded. Could I privately send you the data model and template so you can help me find the solution?

**Comment by zapov** [comment]
The usual way is through trial and error. Trying to make a smaller reproducible until you figured out whats wrong.
The best I can do to help you is if you upload such small reproducible here to see whats wrong (what Editor will point to).
So I suggest to strip private/sensitive information from the template, make it as simple as possible and provide JSON along which reproduces the wrong behavior.

**Comment by zapov** [comment]
I've debugged your project in Templater Editor.
You can see that after first resize it duplicates your entire document which is probably not what you wanted
![resize-issue](https://user-images.githubusercontent.com/1181401/227712097-27b658e3-7576-42b8-8864-9ab996da15e6.png)
To fix this you need to create a region around the part which you want to resize, eg if you create continuous section break before 1st section and before 2nd section, such as
![section-break](https://user-images.githubusercontent.com/1181401/227712133-f567b27a-56f1-4691-a9e1-375502754d07.png)
Then this resize will only affect the region within this 2 section breaks.
![with-sections](https://user-images.githubusercontent.com/1181401/227712183-00d7b2b2-fed9-46dd-aa4d-8cb0e30c7cd0.png)

**Comment by albertobelardi** [comment]
Thanks a lot for your support.
