### ISSUE TITLE
Possible to combine two Word documents?

### ISSUE THREAD

**Issue by solsticesurfer** [ngs-doo/TemplaterExamples#67]
Is there an example of how to combine two Word documents together? I looked through the awesome collection of example programs but did not see this covered.

**Comment by zapov** [comment]
The closest example would be this: https://github.com/ngs-doo/TemplaterExamples/tree/master/Intermediate/HtmlToWord
But it will work for relatively simple documents, as headers and similar features are not really embedded nicely.
If you want actual merging I would look into other solutions

**Comment by solsticesurfer** [comment]
Thanks, that was the initial course that I took and my results were the same with headers/footers.
