### ISSUE TITLE
New Release for 8.0.0?

### ISSUE THREAD

**Issue by asmaier** [ngs-doo/TemplaterExamples#69]
Will there be a new release of Templater builds for v8.0.0 of the Templater library?

**Comment by zapov** [comment]
There will be v8.1 release with various changes, fixes and improvements if this is what you are asking?
Is there some bug in v8.0.0 to ask such a question?

**Comment by asmaier** [comment]
The latest release available at https://github.com/ngs-doo/TemplaterExamples/releases is from Version 7.1.0. That is why I was asking about v8.0.0.

**Comment by zapov** [comment]
Ah, ok. Will find some time for it and upload a new build

**Comment by zapov** [comment]
Released

**Comment by asmaier** [comment]
Thank you very much.
