### ISSUE TITLE
There'is a sample using a two-columns list in DOCX?

### ISSUE THREAD

**Issue by penihel** [ngs-doo/TemplaterExamples#7]
There'is a sample using a two-columns list in DOCX?

**Comment by zapov** [comment]
Hi, by two columns list do you mean Word feature to split page into multiple columns, such as: Label example on http://templater.info/demo (or https://github.com/ngs-doo/TemplaterExamples/tree/master/Beginner/Labels%20(.NET))
do you mean list with multiple levels, such as: https://github.com/ngs-doo/TemplaterExamples/tree/master/Intermediate/ListsAndTables%20(.NET)
or do you mean something else?

**Comment by penihel** [comment]
I have a 4 level nested list. And i want the last level in two-columns layout. The first three are normal, just the fourth have to be splited in two-columns. 

Do you got it?

**Comment by penihel** [comment]
[Resolucao.docx](https://github.com/ngs-doo/TemplaterExamples/files/1528041/Resolucao.docx)

**Comment by zapov** [comment]
Something like this: 

[Resolucao.docx](https://github.com/ngs-doo/TemplaterExamples/files/1528319/Resolucao.docx)

with sample data:

    {"ArtigosRequerimentos":[
    	{"TextoArtigo":"test 1",
    	"TiposRequerimentos":[
    		{"Marcador":"ma 1", "Nome":"no 1",
    		"RequerimentosAgrupadosPorData":[
    			{"Data":"da 1",
    			"Requerimentos":[
    				{"NumeroRegistro":"nu1", "NomeRazaoSocial":"ns1"},
    				{"NumeroRegistro":"nu2", "NomeRazaoSocial":"ns2"},
    				{"NumeroRegistro":"nu3", "NomeRazaoSocial":"ns3"}
    			]},
    			{"Data":"da 2",
    			"Requerimentos":[
    				{"NumeroRegistro":"nu1-2", "NomeRazaoSocial":"ns1-2"},
    				{"NumeroRegistro":"nu2-2", "NomeRazaoSocial":"ns2-2"},
    				{"NumeroRegistro":"nu3-2", "NomeRazaoSocial":"ns3-2"}
    			]}
    		]},
    		{"Marcador":"ma 2", "Nome":"no 2",
    		"RequerimentosAgrupadosPorData":[
    			{"Data":"da 3",
    			"Requerimentos":[
    				{"NumeroRegistro":"nu5", "NomeRazaoSocial":"ns5"},
    				{"NumeroRegistro":"nu6", "NomeRazaoSocial":"ns6"},
    				{"NumeroRegistro":"nu7", "NomeRazaoSocial":"ns7"}
    			]},
    			{"Data":"da 2",
    			"Requerimentos":[
    				{"NumeroRegistro":"nu5-2", "NomeRazaoSocial":"ns5-2"},
    				{"NumeroRegistro":"nu6-2", "NomeRazaoSocial":"ns6-2"},
    				{"NumeroRegistro":"nu7-2", "NomeRazaoSocial":"ns7-2"}
    			]}
    		]}
    	]},
    	{"TextoArtigo":"test 2",
    	"TiposRequerimentos":[
    		{"Marcador":"2ma 1", "Nome":"2no 1",
    		"RequerimentosAgrupadosPorData":[
    			{"Data":"2da 1",
    			"Requerimentos":[
    				{"NumeroRegistro":"2nu1", "NomeRazaoSocial":"2ns1"},
    				{"NumeroRegistro":"2nu2", "NomeRazaoSocial":"2ns2"}
    			]},
    			{"Data":"2da 2",
    			"Requerimentos":[
    				{"NumeroRegistro":"2nu1-2", "NomeRazaoSocial":"2ns1-2"},
    				{"NumeroRegistro":"2nu2-2", "NomeRazaoSocial":"2ns2-2"},
    				{"NumeroRegistro":"2nu3-2", "NomeRazaoSocial":"2ns2-2"},
    				{"NumeroRegistro":"2nu4-2", "NomeRazaoSocial":"2ns3-2"}
    			]}
    		]},
    		{"Marcador":"2ma 2", "Nome":"2no 2",
    		"RequerimentosAgrupadosPorData":[
    			{"Data":"da 5",
    			"Requerimentos":[
    				{"NumeroRegistro":"X-nu5", "NomeRazaoSocial":"X-ns5"},
    				{"NumeroRegistro":"X-nu7", "NomeRazaoSocial":"X-ns7"}
    			]},
    			{"Data":"da 7",
    			"Requerimentos":[
    				{"NumeroRegistro":"X-nu5-2", "NomeRazaoSocial":"X-ns5-2"},
    				{"NumeroRegistro":"X-nu7-2", "NomeRazaoSocial":"X-ns7-2"}
    			]}
    		]}
    	]}	
    ]}

and with helper app from https://github.com/ngs-doo/TemplaterExamples/releases/tag/v2.8.0

    TemplaterJson.exe Resolucao.docx test.json out.docx

**Comment by zapov** [comment]
@penihel is that what you were looking for or you wanted something else?

**Comment by penihel** [comment]
Not exactly.
In your example, you show a table with two columns, but each column contains a field from the same record.
I need a table with two columns, but in the left column a field of the first record, and the right column the same field of the second record.

Finally I ended up using a workaround.

I created an object that contains two properties: Left and Right

And I made a list of this object by mounting an object with 2 records from the normal list.

**Comment by zapov** [comment]
This works as expected in v2.8.3 but it requires a slight modifications to the document:

[ResolucaoSections.docx](https://github.com/ngs-doo/TemplaterExamples/files/1964860/ResolucaoSections.docx)

Templater will only resize tables (nesting) in the expected way if they are not a single table, but rather a separate one. This can be done with a section break as in the above document
