### ISSUE TITLE
How to use collapseIf plugin multiple times for the same tag?

### ISSUE THREAD

**Issue by Kobus-Smit** [ngs-doo/TemplaterExamples#71]
Hi @zapov 

We have a template where we conditionally show certain tables and/or list entries, using a `showIf` custom plugin.
It works in a simple template, but not in a more complicated template where we use `showIf` for the same `tagValue` with multiple `expression` multiple times in the document. It would correctly collapse at some places, but not at other places later in the template etc.

I could reproduce our issue by running the [CollapseRegion](https://github.com/ngs-doo/TemplaterExamples/blob/5b9f6aa347c8cad627da8cf21c911bb88361b0c7/Intermediate/CollapseRegion/CollapseRegion.csproj) example with this template: [Collapse.docx](https://github.com/ngs-doo/TemplaterExamples/files/15343199/Collapse.docx)

I just modified the example's [Collapse.docx](https://github.com/ngs-doo/TemplaterExamples/blob/5b9f6aa347c8cad627da8cf21c911bb88361b0c7/Intermediate/CollapseRegion/template/Collapse.docx)  by
1. Copying `UC check message: [[ucCheckResponse]:collapseIf(Ok)]`  under `Application` and pasting it under `Applicant` twice
2. Then modify the second one to `OK UC check message: [[ucCheckResponse]:collapseIf(Not good enough)]`

![image](https://github.com/ngs-doo/TemplaterExamples/assets/11263864/d4439c6d-2e64-4a31-a4e0-ef44441d846e)

Expected: [Collapse-Result-Expected.docx](https://github.com/ngs-doo/TemplaterExamples/files/15343218/Collapse-Result-Expected.docx)

![image](https://github.com/ngs-doo/TemplaterExamples/assets/11263864/ee903353-71bf-4522-85bd-81d451874dae)

Actual:  [Collapse-Result-Wrong.docx](https://github.com/ngs-doo/TemplaterExamples/files/15343239/Collapse-Result-Wrong.docx)

![image](https://github.com/ngs-doo/TemplaterExamples/assets/11263864/c5a9ea1b-9aab-4af9-9e2c-3fd421002f74)

It does work with a simpler template:  [Collapse-Minimal-Works.docx](https://github.com/ngs-doo/TemplaterExamples/files/15343241/Collapse-Minimal-Works.docx)

Result: [Collapse-Minimal-Works-Result.docx](https://github.com/ngs-doo/TemplaterExamples/files/15343243/Collapse-Minimal-Works-Result.docx)

![image](https://github.com/ngs-doo/TemplaterExamples/assets/11263864/043f4318-f34c-4512-b867-9d04305d0a2e)

Any ideas how I can get the first template to work by modifying the `customIf` plugin?

Thanks,
Kobus

**Comment by zapov** [comment]
While there are certain changes you could do with customIf plugin (eg return ThisTag or CurrentContext) the main change is to use a different repeating region.
If Templater detects multiple repeating regions it will behave slightly different then when it detects multiple tables.
It will process each table on its own, while with this special regions it will try to find common/parent document part for all of those regions.

So one change you need to do is instead of repeating regions use tables without borders.
But this only partly solves the problem as it seems in this case you also need to help Templater a bit with `:all` metadata. In which case it will continue over other tags. I will look if this can be improved in the future not to require this all metadata, but this should get you the behavior you are expecting.
[Collapse.docx](https://github.com/ngs-doo/TemplaterExamples/files/15344790/Collapse.docx)

**Comment by Kobus-Smit** [comment]
Thanks @zapov 

I had tried all the `Handled.` enums in the `customIf` plugin and it did not work for me.

I modified my Collapse.docx by adding the `:all` and moving the `[[ucCheckResponse...` into borderless tables (similar to your attachment) and it works fine.

But adding `:all` did not help with my larger template and custom plugin. Also not sure where and when I should add `:all` and if I can just add it to all tags to be safe (though ugly)? (I added `:all` to your Collapse.docx and it still worked fine there)

My template's tags are already in borderless tables, I toggle `View Gridlines` to show it:
![image](https://github.com/ngs-doo/TemplaterExamples/assets/11263864/8faa2bcb-62cb-46b3-aead-ea4e0af27457)

For example when debugging [Templater-Issue-71.docx](https://github.com/ngs-doo/TemplaterExamples/files/15348022/Templater-Issue-71.docx) 

Up to step 18 is correct (for SMB data)
![image](https://github.com/ngs-doo/TemplaterExamples/assets/11263864/aeb43e20-2057-40db-8548-0123a4fda529)

But then step 19 removes the the wrong table...
![image](https://github.com/ngs-doo/TemplaterExamples/assets/11263864/b221958e-3fa9-4179-9616-e599496c6a9d)

Step 20 removes the correct table.

**Comment by Kobus-Smit** [comment]
[TemplaterPlugin.zip](https://github.com/ngs-doo/TemplaterExamples/files/15349081/TemplaterPlugin.zip)

**Comment by zapov** [comment]
So it turns out this is due to implementation of this plugin which uses smart low level `resize(string[], 0)` instead of exact low level `resize(tag position[], 0)`. I will change this example implementation to use the explicit one down the line so reduce future confusion
