### ISSUE TITLE
In-cell drop-down is Excel not processed correctly?

### ISSUE THREAD

**Issue by asmaier** [ngs-doo/TemplaterExamples#78]
I have a file with a table, where two columns (E and F) consist of values, which the user can select from a in-cell drop-down list

![test_dropdown](https://github.com/user-attachments/assets/f2fb1ff0-0385-4f0a-976a-28134065e3b0)

The row A2 to F2 is marked as range. However when I process some example data with templater like

    java -jar templater-json.jar test_dropdown.xlsx test_data.json test_dropdown_out.xlsx

the the output cells in column E and F will not be in-cell drop-downs anymore:

![test_dropdown_out](https://github.com/user-attachments/assets/0ed2f4a1-d491-4f6b-9fcb-efc852a39b32)

It seems to me templater is just reading the value of the cell, but does not seem to recognize, that the cell allows for a selection of values from a drop-down list. 

Am I doing something wrong here? Or is this not something not possible with templater?

Here are the test files:

[test_data.json](https://github.com/user-attachments/files/16373887/test_data.json)
[test_dropdown_processed.xlsx](https://github.com/user-attachments/files/16373888/test_dropdown_processed.xlsx)
[test_dropdown.xlsx](https://github.com/user-attachments/files/16373889/test_dropdown.xlsx)

**Comment by zapov** [comment]
This Excel features does not seem to be supported currently.
I'll look into what would it take to support it.

**Comment by asmaier** [comment]
Thank you for the quick response. This feature would be really interesting for my employer, because they have many Excel sheets with these dropdown lists.

**Comment by zapov** [comment]
v8.1.0 released and this is now supported

**Comment by asmaier** [comment]
Wow, thank you very much!
