### ISSUE TITLE
How to define context/scope for nested collection in a right way?

### ISSUE THREAD

**Issue by Thor-** [ngs-doo/TemplaterExamples#8]
I've faced with a strange problem, kind of nested collections mixing between items of the parent collection.

[Template](https://www.dropbox.com/s/u38lvazvdmrtnxu/template.docx?dl=0)
[Result](https://www.dropbox.com/s/rsxe6noudy45019/result.docx?dl=0)
[JSON data](https://www.dropbox.com/s/i5195qiyoh5ab30/data.json?dl=0)

JSON:

```
{
  "onSigners": [
    {
      "seaman": {
        "rankName": "Master",
        "plannedVesselName": "ACHILLEAS",
        "joinDate": "2017-09-05T00:00:00Z",
        "firstName": "VALENTYN",
        "birthDate": "1958-01-01T00:00:00Z",
        "nationalityName": null,
        "birthPlace": "MOLDOVA"
      },
      "documents": { }
    },
    {
      "seaman": {
        "rankName": "3rd Officer",
        "plannedVesselName": "ACHILLEAS",
        "joinDate": "2017-09-05T00:00:00Z",
        "firstName": "OLEKSANDR",
        "birthDate": "1988-01-01T00:00:00Z",
        "nationalityName": "Ukrainian",
        "birthPlace": "UKRAINE"
      },
      "documents": {
        "0002": {
          "abbreviation": "0002",
          "name": "SEAMAN'S BOOK",
          "issueDate": "2007-08-15T00:00:00Z",
          "validDate": "2017-04-10T00:00:00Z"
        },
        "0001": {
          "abbreviation": "0001",
          "name": "INTERNATIONAL PASSPORT",
          "issueDate": "2007-07-17T00:00:00Z",
          "validDate": "2017-07-17T00:00:00Z",
          
        }
      }
    }
  ],
  "offSigners": [
    {
      "seaman": {
        "rankName": "Master",
        "plannedVesselName": "ACHILLEAS",
        "joinDate": "2017-09-05T00:00:00Z",
        "firstName": "VALENTYN",
        "mediumName": "",
        "birthDate": "1958-01-01T00:00:00Z",
        "nationalityName": null,
        "birthPlace": "MOLDOVA"
      },
      "documents": {
        
      }
    }
  ]
}
```

**documents** property is a IDictionary type (C#)
As you can see the first item of the onSigners collection doesn't has any documents
![screen](https://user-images.githubusercontent.com/8549305/35777883-277af4a8-09be-11e8-88bc-29188fb43c26.png)

Finally I've tried wrap it in tables but it changed nothing.

I would appreciate any suggestions
Thanks

**Comment by zapov** [comment]
Your template definition looks fine, but Templater handles undefined and null differently.
It should work if you use

    "documents": { 
      "0002": null,
      "0001": null	  
    }

instead of 


    "documents": {  }

I've seen people already having problem with that distinction... and I might add some configuration option in builder to control such a behavior. Of course, if you used classes instead of Dictionary, such a problem would not exists ;)

**Comment by Thor-** [comment]
Thanks, it works!

> I might add some configuration option in builder to control such a behavior.
I think it would be very actual for dynamic data
