### ISSUE TITLE
Excel Report, Diagram is not moving down if above is a list of values

### ISSUE THREAD

**Issue by Streissi** [ngs-doo/TemplaterExamples#9]
Hi,

i have a problem with a diagram. The diagram is placed under a list with some columns (so place diagram at the right side of list is not possible) and some rows. When i generate the report with the templater library it adds the rows but the diagram is not moving down so it is placed over the rows.
Also the data area of the diagram is not moving down. The data area is a second list under the first list.
Here is my ReportTemplate i am using:
[DelayTimeTemplate.xlsx](https://github.com/ngs-doo/TemplaterExamples/files/3203147/DelayTimeTemplate.xlsx)

Do i am something wrong or, missing some setting or anything?

**Comment by zapov** [comment]
Your template has wider area for categories than it ought to (at least without using fixed metadata)
If you change the chart data source (Chart data range) to be ='DelayTimes'!$A$13:$B$13

When paired with input such as 
```[
	{"DelayTimeCategoryName":"CAT-1","Percentage":0.12},
	{"DelayTimeCategoryName":"CAT-2","Percentage":0.55},
	{"DelayTimeCategoryName":"CAT-3","Percentage":0.26}
]```

it will adjust to the expected size, populate the values and update the chart.

I usually test it by using prebuilt JSON tools: https://github.com/ngs-doo/TemplaterExamples/releases/tag/v3.1.0
and by running it from command line:  

    java -jar templater-json.jar DelayTimeTemplate.xlsx delay.json out.xlsx

As far as pushdown of the diagram is concerned, this is not supported in v3.1
Pushdown of pictures and similar objects also does not work.

But... this is actually being worked on right now and will be released in v3.2
If you are interested in testing it before it's released let me know and I can give you link for the download  of v3.2 RC (should be ready for testing by the end of this week)

**Comment by Streissi** [comment]
Hi i tested it.
With the diagram this is no problem i can move it to an other sheet.
But the range (data area) of the diagram is not moving when i add a list above.

I tested it with the following json:
```
{
  "Subtitle":"Title",
  "Delays": [
    {"StartTime":1,"EndTime":2,"Duration":3,"Shift":4,"CategoryName":"Test"},
    {"StartTime":1,"EndTime":2,"Duration":3,"Shift":4,"CategoryName":"Test"},
    {"StartTime":1,"EndTime":2,"Duration":3,"Shift":4,"CategoryName":"Test"},
    {"StartTime":1,"EndTime":2,"Duration":3,"Shift":4,"CategoryName":"Test"}
  ],
  "Total":[
    {"SumDuration":15}
  ],
  "Categories":[
    {"DelayTimeCategoryName":"CAT-1","Percentage":0.12},
    {"DelayTimeCategoryName":"CAT-2","Percentage":0.55},
    {"DelayTimeCategoryName":"CAT-3","Percentage":0.26}
  ]
}
```

I also updated the report template:
[DelayTimeTemplate.xlsx](https://github.com/ngs-doo/TemplaterExamples/files/3206125/DelayTimeTemplate.xlsx)

I'm interested to test the v3.2RC, because the Templater library is a great idea and it works well, but i am more happy if moving diagrams would also work :)

**Comment by zapov** [comment]
There is a snapshot build of the new version at: https://tools.dsl-platform.com/ (both .NET and Java)
It should work now for your use case (diagram will also be pushed down so you don't need to move it onto another sheet).
There are still several things to wrap up before I can release a new version.

**Comment by zapov** [comment]
v3.2.0 has been released. This show now work as expected
